ProjetoEstudo/Models/ErrorViewModel.cs
using System;

namespace ProjetoEstudo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoEstudo/Models/PassageiroModel.cs
using System.ComponentModel.DataAnnotations;

namespace ProjetoEstudo.Models
{
    public class PassageiroModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Informe o Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Informe o Email")]
        [EmailAddress(ErrorMessage = "Digite o e-mail corretamente")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Informe o Cpf")]
        public string Cpf { get; set; }

        [Required(ErrorMessage = "Informe o Numero da Poltrona")]
        public string NumeroPoltrona { get; set; }

        [Required(ErrorMessage = "Informe a Compania")]
        public string Compania { get; set; }

        [Required(ErrorMessage = "Informe a Origem")]
        public string Origem { get; set; }

        [Required(ErrorMessage = "Informe o Destino")]
        public string Destino { get; set; }
    }
}

ProjetoEstudo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjetoEstudo.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoEstudo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoEstudo/Controllers/PassageiroController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoEstudo.Models;
using ProjetoEstudo.Repositorio.Interface;
using System.Collections.Generic;

namespace ProjetoEstudo.Controllers
{
    public class PassageiroController : Controller
    {
        private readonly IPassageiroRepositorio _passageiroRepositorio;

        public PassageiroController(IPassageiroRepositorio passageiroRepositorio)
        {
            this._passageiroRepositorio = passageiroRepositorio;
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            PassageiroModel passageiro = _passageiroRepositorio.ListarPorId(id);
            return View(passageiro);
        }

        [HttpPost]
        public IActionResult Cadastrar(PassageiroModel passageiro)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    _passageiroRepositorio.Adicionar(passageiro);
                    TempData["MensagemSucesso"] = "Passageiro cadastrado com sucesso";
                    return RedirectToAction("Consultar");
                }

                return View(passageiro);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Passageiro não foi cadastrado, tente novamente, erro: {erro.Message}";
                return RedirectToAction("Consultar");
            }
        }

        public IActionResult Consultar()
        {
            List<PassageiroModel> listar = _passageiroRepositorio.ListarTodos();
            return View(listar);
        }

        public IActionResult Editar(int id)
        {
            PassageiroModel passageiro = _passageiroRepositorio.ListarPorId(id);
            return View(passageiro);
        }

        [HttpPost]
        public IActionResult Alterar(PassageiroModel passageiro)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _passageiroRepositorio.Atualizar(passageiro);
                    TempData["MensagemSucesso"] = "Passageiro atualizado com sucesso";
                    return RedirectToAction("Consultar");
                }
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Passageiro não foi atualizado, tente novamente, erro: {erro.Message}";
                return RedirectToAction("Consultar");
            }

            return View("Editar", passageiro);
        }
    }
}

ProjetoEstudo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina Inicial";
}

<div class="text-center">
    <h1 class="display-4">Seja Bem vindo ao Sistema</h1>
    <p>Desenvolver sistema para controlar Estoque de passageiro  </p>
</div>

ProjetoEstudo/Views/Passageiro/ApagarConfirmacao.cshtml
@model PassageiroModel
@{
    ViewData["Title"] = "Apagar Registro Passageiro";
}

<div class="text-center">
    <h2 class="display-4">Confirmação da deleção(@Model.Nome)?</h2>
</div>


<a role="button" asp-controller="Passageiro" asp-action="Consultar" class="btn btn-danger btn-block">Voltar</a>
<a role="button" asp-controller="Passageiro" asp-action="Apagar" class="btn btn-primary btn-block">Confirmação da exlusão</a>

ProjetoEstudo/Views/Passageiro/Cadastrar.cshtml
@model PassageiroModel
@{
    ViewData["Title"] = "Cadastrar Passageiro";
}

<div class="text-center">
    <h2 class="display-4">Cadastrar Pasageiro</h2>
</div>

<form asp-controller="Passageiro" asp-action="Cadastrar" method="post">
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o Nome">
    @Html.ValidationMessageFor(x => x.Nome)
  </div>
  <div class="form-group">
    <label for="e-mail">E-mail</label>
    <input type="text" asp-for="Email" class="form-control" placeholder="Digite o Email">
    @Html.ValidationMessageFor(x => x.Email)
  </div>
  <div class="form-group">
    <label for="cpf">Cpf</label>
    <input type="text" asp-for="Cpf" class="form-control" placeholder="Digite o Cpf">
    @Html.ValidationMessageFor(x => x.Cpf)
  </div>
  <div class="form-group">
    <label for="numeroPoltrona">Numero da Poltrona</label>
    <input type="text" asp-for="NumeroPoltrona" class="form-control" placeholder="Digite o numero da Poltrona">
    @Html.ValidationMessageFor(x => x.NumeroPoltrona)
  </div>
  <div class="form-group">
    <label for="compania">Compania</label>
    <input type="text" asp-for="Compania" class="form-control" placeholder="Digite a Compania">
    @Html.ValidationMessageFor(x => x.Compania)
  </div>
  <div class="form-group">
    <label for="origem">Origem</label>
    <input type="text" asp-for="Origem" class="form-control" placeholder="Digite a Origem">
    @Html.ValidationMessageFor(x => x.Origem)
  </div>
  <div class="form-group">
    <label for="origem">Destino</label>
    <input type="text" asp-for="Destino" class="form-control" placeholder="Digite o Destino">
    @Html.ValidationMessageFor(x => x.Destino)
  </div>
  <button type="submit" class="btn btn-primary btn-block">Cdaastrar Passageiro</button>
</form>

ProjetoEstudo/Views/Passageiro/Consultar.cshtml
@model List<PassageiroModel>
@{
    ViewData["Title"] = "Consultar Passageiro";
}

<div class="text-center">
    <h2 class="display-4">Consultar Pasageiro</h2>
</div>

  <br/>

    @if(TempData["MensagemSucesso"] != null)
    {
         <div class="alert alert-success" role="alert">
           <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
           @TempData["MensagemSucesso"]
        </div>   
    }

    @if(TempData["MensagemErro"] != null)
    {
         <div class="alert alert-success" role="alert">
           <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
           @TempData["MensagemErro"]
        </div>   
    }

    <br/>

<table class="table" id="table-passageiros">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col">Cpf</th>
      <th scope="col">Numwero da Poltrona</th>
      <th scope="col">Compania</th>
      <th scope="col">Origem</th>
      <th scope="col">Destino</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    @if(Model != null && Model.Any())
    {
        foreach(var passageiro in Model)
        {
                <tr>
                  <th scope="row">@passageiro.Id</th>
                  <td>@passageiro.Nome</td>
                  <td>@passageiro.Email</td>
                  <td>@passageiro.Cpf</td>
                  <td>@passageiro.NumeroPoltrona</td>
                  <td>@passageiro.Compania</td>
                  <td>@passageiro.Origem</td>
                  <td>@passageiro.Destino </td>
                  <td>
                     <a role="button" asp-controller="Passageiro" asp-action="Editar" asp-route-id="@passageiro.Id" class="btn btn-primary">Editar</a>
                     <a role="button" asp-controller="Passageiro" asp-action="ApagarConfirmacao" asp-route-id="@passageiro.Id" class="btn btn-danger">Apagar</a>
                 </td>
               </tr>  
        }
    }
  </tbody>
</table>

ProjetoEstudo/Views/Passageiro/Editar.cshtml
@model PassageiroModel
@{
    ViewData["Title"] = "Editar Passageiro";
}

<div class="text-center">
    <h2 class="display-4">Editar Pasageiro</h2>
</div>

<form asp-controller="Passageiro" asp-action="Alterar" method="post">
  <input type="hidden" asp-for="Id"/>
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o Nome">
    @Html.ValidationMessageFor(x => x.Nome)
  </div>
  <div class="form-group">
    <label for="e-mail">E-mail</label>
    <input type="text" asp-for="Email" class="form-control" placeholder="Digite o Email">
    @Html.ValidationMessageFor(x => x.Email)
  </div>
  <div class="form-group">
    <label for="cpf">Cpf</label>
    <input type="text" asp-for="Cpf" class="form-control" placeholder="Digite o Cpf">
    @Html.ValidationMessageFor(x => x.Cpf)
  </div>
  <div class="form-group">
    <label for="numeroPoltrona">Numero da Poltrona</label>
    <input type="text" asp-for="NumeroPoltrona" class="form-control" placeholder="Digite o numero da Poltrona">
    @Html.ValidationMessageFor(x => x.NumeroPoltrona)
  </div>
  <div class="form-group">
    <label for="compania">Compania</label>
    <input type="text" asp-for="Compania" class="form-control" placeholder="Digite a Compania">
    @Html.ValidationMessageFor(x => x.Compania)
  </div>
  <div class="form-group">
    <label for="origem">Origem</label>
    <input type="text" asp-for="Origem" class="form-control" placeholder="Digite a Origem">
    @Html.ValidationMessageFor(x => x.Origem)
  </div>
  <div class="form-group">
    <label for="origem">Destino</label>
    <input type="text" asp-for="Destino" class="form-control" placeholder="Digite o Destino">
    @Html.ValidationMessageFor(x => x.Destino)
  </div>
  <button type="submit" class="btn btn-primary btn-block">Alterar Passageiro</button>
</form>

ProjetoEstudo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoEstudo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projeto de passageiro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Passageiro" asp-action="Cadastrar">Cadastro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Passageiro" asp-action="Consultar">Consulta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Desenvolvido por Gustavo Gregório
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
     <script src="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>